# Netlify build configuration

[build]
  # The folder containing your site files; '.' means the repo root
  publish = "."

[build.environment]
  # Cloudinary configuration
  CLOUDINARY_CLOUD_NAME = "venusiana-boutique"

# Disable automatic image optimization if not needed
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = false

# Optional: Check for broken links
[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    # You can leave this empty or configure valid inputs like entryPoints, recursive, etc.


    

