[build]
  # This is a static HTML site, no build command needed
  publish = "."
  command = ""

[build.environment]
  # Basic environment variables for static site
  NODE_ENV = "production"
  
  # Cloudinary environment variable (set to demo value if not provided)
  CLOUDINARY_CLOUD_NAME = "venusiana-demo"

# Headers for static assets
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules (optional)
# [[redirects]]
#   from = "/old-page"
#   to = "/new-page"
#   status = 301