# Netlify build configuration

[build]
  publish = "."
  
[build.environment]
  CLOUDINARY_CLOUD_NAME = "venusiana-boutique"

# Disable automatic image optimization if not needed
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = false

# Netlify plugin: check for broken links, but do not fail the build
[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    failOnError = false
